version: "3.9"
services:
  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    depends_on: ["backend"]

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on: ["minio", "mongo"]

  agent-manager:
    build:
      context: ./agent-manager
    ports:
      - "8080:8080"
    depends_on: ["minio", "mongo"]

  minio:
    image: quay.io/minio/minio
    volumes: ["disk:/data"]
    command: server /data --console-address :9001
    env_file: ./env-minio.env
    ports:
      - "9000:9000"
      - "9001:9001"

  mongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=verystrongpassword
    volumes: ["mongo:/data"]
    ports: ["27017:27017"]

volumes:
  disk:
  mongo:
